### ISSUE TITLE
Validator feature is not implemented: `sh:zeroOrMorePaths` and `sh:oneOrMorePaths`

### ISSUE THREAD

**Issue by edmondchuc** [RDFLib/pySHACL#129]
When I run PySHACL with any property shapes containing `sh:zeroOrMorePaths` or `sh:oneOrMorePaths`, I get:

```
Validator feature is not implemented:
That path method to get value nodes of property shapes is not yet implemented.
If your use-case requires this feature, open an Issue on the pyshacl github page.
```

**Comment by edmondchuc** [comment]
Closing due to misspelling of `sh:zeroOrMorePath` and `sh:oneOrMorePath`.

**Comment by ashleysommer** [comment]
Even though this is report is invalid (wrong spelling of the constraint), it has exposed the issue where the shown error is incorrect.

The error about non-implemented path method is no longer relevant to that section of code (all path methods are now implemented) so that should be replaced with a new type of ShapeLoadError, something like "sh:zeroOrMorePaths" is not a valid Path method for `sh:path`, that will help you track down the issue.
