### ISSUE TITLE
pySHACL not validating object property instance ranges?

### ISSUE THREAD

**Issue by tduval-unifylogic** [RDFLib/pySHACL#176]
Greetings. I really like pySHACL, but I have a small issue. It's likely I'm doing something incorrect. 
For some reason, I looked at issue #40 which looks like it has range validation in it, and attempted to recreate with a simple ontology and data graph, but I am not getting a validation error on :event2's range? 

Any insight would be helpful. Thank you.

Here is my code:

Python 3.9.6
rdflib 6.1.1
pySHACL 0.20.0

```
from rdflib import Graph
from pyshacl import validate
onto = """
    @prefix schema: <http://schema.org/> .
    @prefix owl: <http://www.w3.org/2002/07/owl#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
    @prefix sh: <http://www.w3.org/ns/shacl#> .

    schema:Organization a owl:Class .
     schema:Person a owl:Class, sh:NodeShape .

    schema:Event a owl:Class, sh:NodeShape ;
        sh:property [ 
            sh:path schema:attendee ;
            sh:node schema:Person           
        ] .

    schema:attendee a owl:ObjectProperty ;
        rdfs:domain schema:Event ;
        rdfs:range schema:Person 
    .
"""
og = Graph().parse(data=onto, format='turtle')
data = """
    @prefix schema: <http://schema.org/> .
    @prefix owl: <http://www.w3.org/2002/07/owl#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
    @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
    @prefix sh: <http://www.w3.org/ns/shacl#> .
    @prefix : <http://example.org/> .   

    :person1 rdf:type schema:Person .
    :organization1 rdf:type schema:Organization .

    :event1 rdf:type schema:Event ;
        schema:attendee :person1 .
    :event2 rdf:type schema:Event ;
        schema:attendee :organization1 .

"""
data_graph = Graph().parse(data=data, format='turtle')

r = validate(data_graph,
      shacl_graph=og,
      ont_graph=og,
      inference='both',
      abort_on_first=False,
      allow_infos=False,
      allow_warnings=False,
      meta_shacl=True,
      advanced=False,
      js=False,
      debug=False)
conforms, results_graph, results_text = r
print(conforms)
```
Here is the result I get:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/62360524/229631198-68d69a12-8698-4c5f-b575-f0ca2e5b8979.png">

**Comment by ashleysommer** [comment]
Hi @tduval-unifylogic 
PySHACL only validates data against SHACL constraints. `rdfs:range` is helpful for describing a RDFS Schema or Ontology, but it is not a SHACL constraint, and PySHACL ignores it in this example.

To achieve what you want in your example here, you need the SHACL [ClassConstraintComponent](https://www.w3.org/TR/shacl/#ClassConstraintComponent), it validates that a given property is an instance of `Person` or instance of subclass of `Person`.

A working example shapefile would look something like this:

```bash
    @prefix schema: <http://schema.org/> .
    @prefix owl: <http://www.w3.org/2002/07/owl#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
    @prefix sh: <http://www.w3.org/ns/shacl#> .

    schema:Organization a owl:Class .

    schema:Event a owl:Class, sh:NodeShape ;
        sh:name "AttendeeIsPerson" ;
        sh:description "Validates that an event's attendees are instance of class Person." ;
        sh:property [ 
            sh:path schema:attendee ;
            sh:class schema:Person           
        ] .

    schema:Person a owl:Class, sh:NodeShape ;
        sh:name "AttendeeOnEvent" ;
        sh:description "Validates that this person was attendee of instance of Event." ;
        sh:property [ 
            sh:path [ sh:inversePath schema:attendee  ] ;
            sh:class schema:Event           
        ] .

    schema:attendee a owl:ObjectProperty ;
        rdfs:domain schema:Event ;
        rdfs:range schema:Person 
    .
```
or if you want to match the semantics of `rdfs:domain` and `rdfs:range`, instead of targeting the classes, you can target the property itself, like this:

```
    @prefix schema: <http://schema.org/> .
    @prefix owl: <http://www.w3.org/2002/07/owl#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
    @prefix sh: <http://www.w3.org/ns/shacl#> .

    schema:Organization a owl:Class .
    schema:Person a owl:Class .
    schema:Event a owl:Class .
   
    schema:AttendeeIsPerson a sh:NodeShape ;
        sh:targetObjectsOf schema:attendee ;
        sh:description "Validates that an event's attendees are instance of class Person." ;
        sh:path schema:attendee ;
        sh:class schema:Person   .   

    schema:AttendeeOnEvent a sh:NodeShape ;
        sh:targetSubjectsOf schema:attendee ;
        sh:description "Validates that this person was attendee of instance of Event." ;
        sh:class schema:Event   .
```

**Comment by ajnelson-nist** [comment]
@ashleysommer : I think @tduval-unifylogic 's example isn't ignored by SHACL.  There were three things that look to me like they interact and cause the "incorrect" (to eyes) passing validation result.

The three things are these two triples:

```turtle
schema:attendee rdfs:range schema:Person .

:event1 schema:attendee :organization1 .
```

and the `inference='both'` parameter on the call to `validate`.

If inference were `none`, the example would have raised a validation error.  But with `inference='both'`, an additional triple is inferred/expanded/entailed, sufficiently from either RDFS entailment or OWL entailment (IIRC, either entailment scheme would cause this; at least RDFS does):

```turtle
:organization1 a schema:Person .
```

So, the SHACL property shape from @tduval-unifylogic is satisfied after RDFS (and/or OWL) entailment has occurred.

**Comment by tduval-unifylogic** [comment]
@ajnelson-nist thanks so much for your explanation! 
It makes total sense now and I am getting the result I expect...

Shameless plug (since you folks are into reasoners):
Please check out the recently published N3 Builtin Functions Documentation: https://domel.github.io/n3builtins/specification/

**Comment by ashleysommer** [comment]
@ajnelson-nist  @tduval-unifylogic 

> There were three things that look to me like they interact and cause the "incorrect" (to eyes) passing validation result.
> If inference were none, the example would have raised a validation error. 

I agree with you that there is an issue with rdfs:range and rdfs:domain in schema.org, and it is something they need to address.

However it doesn't change my original answer. There are only two SHACL Shapes in the example given. One is on `schema:Event` and the other is on `schema:Person`. The first shape has only one constraint, it is the `sh:property` constraint, and it triggers the second shape `schema:Person`, that has _no_ SHACL constraints defined on it. The `rdfs:range` and `rdfs:domain` declarations are not SHACL constraints, and are not used by PySHACL.

PySHACL sees no constraints to run, so the result is a passing validation result. Whether 'rdfs' inferencing is used or not is irrelevant, because when running this example in a python debugger and stepping through the code, it is easy to see the validator exists early with a passing validation result after finding no constraints to test.
