### ISSUE TITLE
Release for RDFLib 7.0

### ISSUE THREAD

**Issue by aucampia** [RDFLib/pySHACL#197]
@ashleysommer We fixed a bug in RDFLib 7.0 relating to HTML handling (https://github.com/RDFLib/rdflib/issues/2475), and @floresbakker is using RDFLib and pySHACL for some efforts on [the Semantic HTML-vocabulary Community Group](https://www.w3.org/community/htmlvoc/).

I will make some PRs to update pySHACL for RDFLib 7.0 this weekend, it should not need much as the changes are probably not break anything that pySHACL does, but I can also proceed with a release if you are open to it.

**Comment by ashleysommer** [comment]
Hi @aucampia 
Thanks for raising this. I usually try to keep compatibility in PySHACL for the three most recent releases of RDFLib, because it is common for users of PySHACL to need the latest version of PySHACL, but earlier versions of RDFLib.

PySHACL is quite a complex codebase, so I normally implement the changes to update PySHACL to new RDFLib versions myself, while using patches and workarounds to maintain compatibility with older RDFLib versions too.

You can raise the PRs on the weekend, and I will review them and do my own testing to ensure everything is good to release, then I will push out a release for you.

**Comment by ashleysommer** [comment]
@aucampia new PySHACL release with compatibility with RDFLib v7.0.0 (and 6.3.2 and 6.2.0) is out now.
