### ISSUE TITLE
Failed to catch violations with properties that are not defined

### ISSUE THREAD

**Issue by mhoangvslev** [RDFLib/pySHACL#215]
Given the datashape below, which is a json-ld markup:

```json
{
    "@context": "http://schema.org",
    "@type": "Product",
    "@id": "https://www.slimmingeats.com/blog/hoisin-chicken-actifry-stove-top",
    "name": "Hoisin Chicken (Actifry or Stove top) | Slimming Eats",
    "description": "Heavenly Tender Hoisin Chicken - a quick simple dish that is ready in less than 20 minutes and can be cooked in an Actifry or on the Stove Top. Gluten Free, Dairy Free, Slimming Eats and Weight Watchers friendly.",
    "url": "https://www.slimmingeats.com/blog/hoisin-chicken-actifry-stove-top",
    "image": "https://www.slimmingeats.com/blog/wp-content/uploads/2016/06/hoisin-chicken-24-480x480.jpg",
    "brand": {
        "@type": "Brand",
        "name": "Slimming Eats"
    },
    "aggregateRating": {
        "@type": "AggregateRating",
        "ratingValue": 5.0,
        "reviewCount": 16
    },
    "offers": {
        "@type": "Offer",
        "price": 0.0,
        "priceCurrency": "USD",
        "availability": "http://schema.org/InStock"
    },
    "recipeCategory": "Main Dish",
    "recipeCuisine": "Chinese",
    "cookTime": "PT26M",
    "nutrition": {
        "@type": "NutritionInformation",
        "calories": "225",
        "totalFat": "2.8g",
        "saturatedFat": "0.1g",
        "cholesterol": "95mg",
        "sodium": "403mg",
        "carbohydrates": "10.3g",
        "fiber": "1.2g",
        "sugar": "5.5g",
        "protein": "39.2g"
    },
  "pouet": "pouet"
}
```

Given the [shape graph](https://datashapes.org/schema.ttl), and the [ontology](https://github.com/schemaorg/schemaorg/blob/main/data/releases/23.0/schemaorg-all-http.ttl), `nutrition` not being a property of `Product` or `Thing`, I expect a violation but there wasn't any.

I ran using:

```bash
pyshacl -e schemaorg-all-http.ttl -s schemaorg-datashapes.ttl -a -im -df json-ld test.json
```

I added `sh:closed true` to `Thing` but I encounter inheritance issues as discussed #167, #141.

I tried to follow the recommendation [here](https://stackoverflow.com/questions/70785194/shacl-closed-shape-with-superclass-inheritance) but then pySHACL reports error:

```bash
Validator encountered a Constraint Load Error:
Cannot select a validator to use, according to the rules.
For reference, see https://www.w3.org/TR/shacl/#constraint-components-validators%     
```

**Comment by ajnelson-nist** [comment]
It looks to me like you've stumbled into an undesired extension of `schema:nutrition`, and you're looking for why it's not prevented by SHACL.  The short answer is, this particular use is part of the open-world behavior of RDF (not necessarily just OWL), and hasn't been closed off by any closed-world rule from SHACL.  schema.org's `rdf:Property`s are written in a way that gently suggests what classes they should be associated with, but using structural predicates that don't trigger behaviors from RDFS or OWL inferencing engines.

First, on trying to flag this as an error from inferencing:  The ontology you linked is not an OWL ontology, and the [nearby OWL transcoding](https://github.com/schemaorg/schemaorg/blob/main/data/releases/23.0/schemaorg.owl) does not include any `owl:disjointWith` statements.  Without `owl:disjointWith`, even if the properties were defined in a way supporting OWL inferencing, you would not find any errors from OWL inferencing by using `schema:nutrition` on something unexpected, like a `schema:Concert`.  The thing using `schema:nutrition` would just become a `schema:Concert` and either a `schema:MenuItem` or `schema:Recipe`.

Neither OWL nor RDFS inferencing using the schema.org ontology (i.e. the RDF Schema or OWL Ontology) would cause new `@type` values to be inferred.  schema.org's properties in the RDF Schema eschew `rdfs:domain`, instead using `schema:domainIncludes` which (IIRC) has no entailment (/inference) semantics to generate new RDF triples.
And, while the OWL transcoding has `rdfs:domain` statements, they all (IIRC - a little hard to grep at a skim) tie to `owl:unionOf` anonymous classes, which need an OWL reasoner to whittle down to a named class from other axioms describing the object.  But again, this still won't raise an error for you, because the OWL transcoding does not include any `owl:disjointWith` statements that would let you arrive at a logical inconsistency.

In a purposefully-unimaginative and closed-world style, I could declare that the set of concerts and set of cooking recipes are disjoint.  But, that's not encoded in schema.org, so I'd need to write a SHACL rule for my own data.  And, respecting imagination and open-world modeling, someone could probably link a video to a counterexample, with a rock band playing while someone's baking a cake.  Depending on any other ontology foundations your graph is built on, that concert could rightly get a nutrition value.

If you wanted to be really careful with your usage of `schema:nutrition` and make sure it only appears on `MenuItem` or `Recipe`, you would need this shape:

```turtle
<urn:example:schema-nutrition-subjects-shape>
a sh:NodeShape ;
sh:or (
  [
    a sh:NodeShape ;
    sh:class schema:MenuItem ;
  ]
  [
    a sh:NodeShape ;
    sh:class schema:Recipe ;
  ]
) ;
sh:targetSubjectsOf schema:nutrition ;
.
```

**Comment by mhoangvslev** [comment]
Thank you for the prompt reply!

If I understand it right, in a few words, schema.org defines what a class is but does not define what a class is not.
Is there a quick way to assume the `owl:disjointWith` relation with all other classes unless specified by the author?

The use case is this:
- I generated a markup and I want to validate it (similar to https://validator.schema.org/ but automatically).
- The schema.org validator is able to say that "nutrition" is not a property of "Product" or any superclass of "Product".

> If you wanted to be really careful with your usage of `schema:nutrition` and make sure it only appears on `MenuItem` or `Recipe`, you would need this shape:

In the shape graph, `nutrition` only appears in `MenuItem` or `Recipe` through:

```turtle

schema:Recipe
  a rdfs:Class ;
  a sh:NodeShape ;
  rdfs:comment "A recipe. For dietary restrictions covered by the recipe, a few common restrictions are enumerated via [[suitableForDiet]]. The [[keywords]] property can also be used to add more detail."^^rdf:HTML ;
  rdfs:label "Recipe" ;
  rdfs:subClassOf schema:HowTo ;
  sh:property schema:Recipe-cookTime ;
  sh:property schema:Recipe-cookingMethod ;
  sh:property schema:Recipe-ingredients ;
  sh:property schema:Recipe-nutrition ;
  sh:property schema:Recipe-recipeCategory ;
  sh:property schema:Recipe-recipeCuisine ;
  sh:property schema:Recipe-recipeIngredient ;
  sh:property schema:Recipe-recipeInstructions ;
  sh:property schema:Recipe-recipeYield ;
  sh:property schema:Recipe-suitableForDiet ;

schema:Recipe-nutrition
  a sh:PropertyShape ;
  sh:path schema:nutrition ;
  sh:class schema:NutritionInformation ;
  sh:description "Nutrition information about the recipe or menu item."^^rdf:HTML ;
  sh:name "nutrition" ;
```

**Comment by mhoangvslev** [comment]
> The shape I sketched would satisfy this use case.
I just updated the example markup to include a rubbish field:
```
"pouet": "pouet"
```

Since I never know what the end user might type, I can't anticipate every misadventure with a shape.

**Comment by mfhepp** [comment]
FYI: Some more background from a schema.org perspective of the problem is in https://github.com/schemaorg/schemaorg/issues/3408#issuecomment-1816721399.

**Comment by mfhepp** [comment]
Quick an practical advice for this an similar data validation tasks: You need to produce **your custom SHACL shapes definitions**, either manually or derived from the RDFS or OWL vocabulary or vocabularies. Neither OWL nor RDFS are particularly suited for defining **constraints regarding the domain or range of properties**. 

After all, that is the entire motivation for the notion of data shapes and shape languages like SHACL; worthwhile reading is e.g. [Tim Berners-Lee's piece *Linked Data Shapes, Forms and Footprints*](https://www.w3.org/DesignIssues/Footprints.html).
