### ISSUE TITLE
Time required for shape validation 

### ISSUE THREAD

**Issue by AJAY31797** [RDFLib/pySHACL#237]
Hi, 

Firstly, thanks for the pySHACL. It kind of makes SHACL validation really easy to implement. 

I have a project in which I need to use SHACL-JS for defining the shape. To test it, I am looking at different environments that support SHACL-JS. I found pySHACL is one of them. So, I tried to run the SHACL validation on it. But to my surprise, it is taking a lot of time to perform the validation. 
Here are the examples of the SHACL shapes and the JS function (wrote just a simple test function).

SHACL shape - 
```
@prefix CSRO: <http://www.semanticweb.org/aagr657/ontologies/2023/9/CraneSpaceRepresentationOntology#> .
@prefix LinkOnt: <http://purl.org/ConstructLinkOnt/LinkOnt#> .
@prefix bot: <https://w3id.org/bot#> . 
@prefix geo: <http://www.opengis.net/ont/geosparql#> . 
@prefix geom: <http://rdf.bg/geometry.ttl#> . 
@prefix ifc: <https://standards.buildingsmart.org/IFC/DEV/IFC2X3/TC1/OWL> . 
@prefix inst: <https://www.ugent.be/myAwesomeFirstBIMProject#> . 
@prefix owl: <http://www.w3.org/2002/07/owl#> . 
@prefix sf: <http://www.opengis.net/ont/sf#> . 
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix smls: <https://w3id.org/def/smls-owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .

inst:checkRotationPossibility
	rdf:type sh:JSFunction ;
	sh:parameter [
		sh:path inst:boomLength;
		sh:datatype xsd:float;
	];
	sh:parameter [
		sh:path inst:setPoint;
		sh:datatype geo:wktLiteral;
	];
	sh:parameter [
		sh:path inst:boomClearance;
		sh:datatype xsd:float;
	];
	sh:parameter [
		sh:path inst:boomMastClearance;
		sh:datatype xsd:float;
	];
	sh:parameter [
		sh:path inst:boommastPendantsClearance;
		sh:datatype xsd:float;
	];
	sh:parameter [
		sh:path inst:lowerRotatingBodyClearance;
		sh:datatype xsd:float;
	];
	sh:parameter [
		sh:path inst:auxiliaryCounterweightClearance;
		sh:datatype xsd:float;
	];
	sh:parameter [
		sh:path inst:pickPoint;
		sh:datatype geo:wktLiteral;
	];
	sh:returnType xsd:boolean;
	sh:jsLibrary [
		# dockerized web server - container called "shacl-x-web"
		sh:jsLibraryURL "https://github.com/AJAY31797/SHACLJS_Test/blob/main/Try_consolelog.js"^^xsd:anyURI
	] ;
	sh:jsFunctionName "detectCraneRotationConstraint" .


inst:boundingBoxIntersectionDetection
	rdf:type sh:NodeShape ;
	sh:target [
		rdf:type sh:SPARQLTarget ; 
		sh:select """
			PREFIX ifc: <https://standards.buildingsmart.org/IFC/DEV/IFC2X3/TC1/OWL>
			PREFIX LinkOnt: <http://purl.org/ConstructLinkOnt/LinkOnt#>
			SELECT $this
			WHERE {
				$this LinkOnt:TaskLevel LinkOnt:SubActivity .
			}
		""" ;
	] ;
	sh:sparql [
		rdf:type sh:SPARQLConstraint ;
		sh:message "Space constraint is violated for focus node: {$this}" ;
		sh:select"""
			PREFIX LinkOnt: <http://purl.org/ConstructLinkOnt/LinkOnt#>
			PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
			PREFIX owl: <http://www.w3.org/2002/07/owl#>
			PREFIX CSRO: <http://www.semanticweb.org/aagr657/ontologies/2023/9/CraneSpaceRepresentationOntology#>
			PREFIX sf: <http://www.opengis.net/ont/sf#>
			PREFIX geo: <http://www.opengis.net/ont/geosparql#>
			PREFIX bot: <https://w3id.org/bot#>
			PREFIX inst: <https://www.ugent.be/myAwesomeFirstBIMProject#>
			PREFIX geom: <http://rdf.bg/geometry.ttl#>
			PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
			SELECT $this
			WHERE {
				$this LinkOnt:HasResource ?resource .
    				?resource a LinkOnt:Resource, CSRO:CrawlerCrane;
					LinkOnt:ResourceType LinkOnt:Equipment;
					CSRO:hasPlacementLocation ?cranePlacementLocation; 
					CSRO:hasComponent ?craneComponent1, ?craneComponent2, ?craneComponent3, ?craneComponent4, ?craneComponent5, ?craneComponent6, ?craneComponent7.

				?craneComponent1 a CSRO:Boom;
					CSRO:hasBoomLength ?boomLength;
					CSRO:hasRequiredClearance ?boomClearance.

				?craneComponent2 a CSRO:BoomMast;
					CSRO:hasRequiredClearance ?boomMastClearance.

				?craneComponent3 a CSRO:BoomMastPendants;
					CSRO:hasRequiredClearance ?boommastPendantsClearance.

				?craneComponent4 a CSRO:LowerRotatingBody;
					CSRO:hasRequiredClearance ?lowerRotatingBodyClearance.

				?craneComponent5 a CSRO:AuxiliaryCounterweight;
					CSRO:hasRequiredClearance ?auxiliaryCounterweightClearance.

				?craneComponent7 a CSRO:ObjectLifted;
					CSRO:hasPickLocation ?pickLocationLiftedObject.

				?pickLocationLiftedObject a sf:Point;
					geo:asWKT ?pickPoint.

            			BIND (inst:checkRotationPossibility(?boomLength, ?setPoint, ?boomClearance, ?boomMastClearance, ?boommastPendantsClearance, ?lowerRotatingBodyClearance, ?auxiliaryCounterweightClearance, ?pickPoint) AS ?result)
            			FILTER (?result = false)
               			}
			""";
		] ;
.
```

JS Function - 

```
function detectCraneRotationConstraint($boomLength, $setPoint, $boomClearance, $boomMastClearance, $boommastPendantsClearance, $lowerRotatingBodyClearance, $auxiliaryCounterweightClearance, $pickPoint){

    console.log($boomLength.getLex());
    console.log($setPoint.getLex());
    console.log($boomClearance.getLex());
    console.log($boomMastClearance.getLex());
    console.log($boommastPendantsClearance.getLex());
    console.log($lowerRotatingBodyClearance.getLex());
    console.log($auxiliaryCounterweightClearance.getLex());
    console.log($pickPoint.getLex());

    return true;
 
}
```

It has been running for more than one hour now, but yet the validation result is not printed. There are just 10 focus nodes in the RDF data. I am not sure why is it happening. I tried the same with SHACL-X (which is another SHACL engine that supports SHACL-JS), which gives the results very quickly (although it is giving some different kinds of errors). Could you suggest anything why this might be happening? I am running pySHACL using VS Code.

The command to ran for validation:
```
from pyshacl import validate
data_graph = "C:/..../data_020724.ttl"
shacl_graph = "C:/..../shapes_rotation_checking_debug.ttl"

r = validate(data_graph = data_graph,
      shacl_graph = shacl_graph,
      ont_graph = None,
      inference='rdfs',
      abort_on_first=False,
      allow_infos=False,
      allow_warnings=False,
      meta_shacl=False,
      advanced=True,
      js=True,
      debug=True)
conforms, results_graph, results_text = r  
```

Here is what I am seeing while the validation command is running:
```
Cloning DataGraph to temporary memory graph before pre-inferencing.
Running pre-inferencing with option='rdfs'.
Found 1 SHACL Shapes defined with type sh:NodeShape.
Found 0 SHACL Shapes defined with type sh:PropertyShape.
Found 0 property paths to follow.
Found 0 implied SHACL Shapes based on their properties.
Found 0 implied SHACL Shapes used as values in shape-expecting constraints.
Cached 1 unique NodeShapes and 0 unique PropertyShapes.
Activating SHACL-AF Features.
Will run validation on 1 named graph/s.
Validating DataGraph named urn:x-rdflib:default
Checking if Shape <NodeShape https://www.ugent.be/myAwesomeFirstBIMProject#boundingBoxIntersectionDetection> defines its own targets.
Identifying targets to find focus nodes.
Milliseconds to find focus nodes: 66.263ms
Found 10 Focus Nodes to evaluate.
Running evaluation of Shape <NodeShape https://www.ugent.be/myAwesomeFirstBIMProject#boundingBoxIntersectionDetection>
Current shape evaluation path: <NodeShape https://www.ugent.be/myAwesomeFirstBIMProject#boundingBoxIntersectionDetection>
Checking conformance for constraint: <SPARQLBasedConstraint on <NodeShape https://www.ugent.be/myAwesomeFirstBIMProject#boundingBoxIntersectionDetection>>   
Current constraint evaluation path: <NodeShape https://www.ugent.be/myAwesomeFirstBIMProject#boundingBoxIntersectionDetection> -> <SPARQLBasedConstraint on <NodeShape https://www.ugent.be/myAwesomeFirstBIMProject#boundingBoxIntersectionDetection>>
```

Thanks a lot!

Best Regards,
Ajay

**Comment by ashleysommer** [comment]
Hi @AJAY31797 
Thanks for submitting this report. After a quick look at your SHACL Shapes and JS function, it seems like it should execute very quickly.  I will test it locally on my system and add some additional profiling to PySHACL to try to determine where the bottleneck is.
PySHACL was the first open-source SHACL-JS implementation, but it has not had much use, it is a niche feature and is not well tested, so this is a good opportunity to optimise the feature for someone who actually uses it.

It there any chance you can provide access to the "data_020724.ttl" file? or an anonymized version of it? That will help with my testing.

**Comment by ashleysommer** [comment]
Hi @AJAY31797
I've synthesized some dummy data to match your shapes, and have narrowed this down.

I identified two errors in the provided files that are preventing this from running as expected.

1) Your SPARQL function requires the resource to have a `?craneComponent6`, but there is no `?craneComponent6` used in the rest of the query. I've added another placeholder component in my synthesized data to fill the role of `?craneComponent6`.

2) The `?setPoint` variable in your SPARQL is unbound. This prevents the SPARQL Function from being able to call the JS function. I fixed this by adding a `wkt:Point` to the value for `hasPlacementLocation`.

After those two were fixed, the JS is executing as expected and I am getting the result `identifier 'console' is undefined` that is because the duktape JS engine used in PySHACL does not support console logging.

There is a third issue I found, the namespace for your `ifc:` prefix must end with either `/` or `#`, but it does not. This will prevent this prefix from working as expected, however it is not relating to this issue because `ifc:` prefix is not used in any of your turtle files.

I'm not sure why you are seeing a long execution time, because in my testing I got an instant execution failure with the SPARQL errors described above, and after fixing those, I got an instant execution of the JS function.

At this stage, I'm going to need a full minimal reproduction of the issue from you before I can narrow it down further.

**Comment by AJAY31797** [comment]
Hi @ashleysommer,

Many thanks for your response. 
Attached are the files that you can use for testing. I have included the complete shape and the complete data that I want to use. The JS function is just a trial function to check how the things work. The actual JS function I want to use involves some mathematical calculations, but I don't think that will affect pySHACL. I have also separately tested the SPARQL function as a query in apache jena fuseki server (avoiding the BIND and FILTER part), and it successfully fetches the results from the RDF data. If you need a smaller version of the data, please let me know. I will then include only the triples related to the query. 

[trial_pySHACL.zip](https://github.com/user-attachments/files/16341072/trial_pySHACL.zip)

On another note, are you using Linux for testing or windows? Just checking to see if that might be the reason for the time being taken for execution. 

Thanks, 

Best Regards,
Ajay

**Comment by ashleysommer** [comment]
> On another note, are you using Linux for testing or windows? Just checking to see if that might be the reason for the time being taken for execution.

I'm using Linux, but I don't think the OS is the issue, the execution time of Linux vs Windows should be roughly equal.

**Comment by ashleysommer** [comment]
@AJAY31797 
I'm seeing the same slowdown now. It is definitely due to the size of the data file. PySHACL uses RDFLib to execute SPARQL queries on the in-memory graph. The RDFLib sparql engine is pure-python, originally written in 2003, it has always been embarrassingly slow, and more so on large datasets (not that 158MB would even be considered large to some people). 

I've tried to get your dataset to work better by loading the datagraph into a PyOxigraph store, and executing the SPARQL query using PyOxigraph's much faster SPARQL engine. However I ran into the problem then that PyOxigraph does not allow you to register custom SPARQL functions, so all of the built-in PySHACL SPARQL features do not work, including calling SHACL-JS functions.

I'll keep thinking on another solution for you.

**Comment by AJAY31797** [comment]
Thanks @ashleysommer,

Yes I have experienced it with RDFLib. It takes a lot of time to run SPARQL queries. 

In my case, I tried running it with considerably reduced dataset as well, but it still is taking too long. I will try running on a higher performance computer to see if it improves. 

Thanks for the help. 

Best Regards,
Ajay

**Comment by AJAY31797** [comment]
Hi @ashleysommer,

So I tried running it on Windows Subsystem For Linux on a computer with better processing capabilities (Intel(R) Xeon(R) Gold 6242R CPU @ 3.10GHz   3.09 GHz  (2 processors)). I followed the following steps:
1. Install pyhacl - 
`pip3 install pySHACL`

2. Install pyduktape2
`pip3 install pyduktape2`

3. Ran the data validation
`pyshacl -s /home/......./shape_trial_git.ttl -m -i rdfs -a -j -f human /home/...../data_trial_git.ttl`

However, this still is taking hours. I am not sure about what the results would be as I haven't received them yet.

Is there any dependency I am missing to install here? Or any process that I am doing wrong here? 

Best Regards,
Ajay

**Comment by ashleysommer** [comment]
Your method is correct. You are doing it right.

I have done more profiling on RDFLib and PySHACL, and I can confirm it is certainly the RDFLib SPARQL executor that is causing the problem. The PySHACL `SPARQLConstraint` sets up the query and the JS function correctly,  it hands off to RDFLib to run the SPARQL query and even after waiting several hours the JS function is never called. You will know when the JS function is executed because pySHACL with crash with the error `identifier 'console' is undefined` but we never see that. During this time, I see one cpu core is pegged at 100% usage, and RAM consumption is around 2GB.

Running the exact same SPARQL constraint with a much smaller simplified graph with only a single compatible focus node executes instantly. It would be good to try it on increasingly large graphs, there must be a tipping point where is flips from "fast enough" to "terribly slow". I don't know if it is a bug in RDFLib or a design issue. RDFLib is single-threaded so running it on larger servers with more cores or more CPUs does not help at all. I don't think adding more RAM would help in any significant way either.

**Comment by AJAY31797** [comment]
Hi @ashleysommer,

Thanks for your response. I will try to incrementally execute it and see if I can find the point of making it terribly slow. It seems that because the query is being executed this slowly, it won't really help me with the intended purpose. So, I will need to see some other solutions. 

Best Regards,
Ajay
