### ISSUE TITLE
Validating files containing multiple named graphs

### ISSUE THREAD

**Issue by RinkeHoekstra** [RDFLib/pySHACL#26]
The `load.py` script currently loads all passed files into an rdflib `Graph` object. For JSON-LD files that contain multiple named graphs, this means that the resulting graph object `g` in the referenced line [1] will be empty, and the validation will succeed without warning.

I know that pySHACL currently does not support TriG or NQuads files, but if you allow for JSON-LD, you should allow for these as well as the big difference is the support for named graphs.

There are three ways around this:

* Show a warning that files containing named graphs cannot currently be validated (not ideal, as this should be easy to fix).
* Simple quick fix is to load files into a `ConjunctiveGraph`. This disregards all named graph information, but makes all triples available for validation. This is the behaviour of the SHACL playground implementation. This is not ideal either, as we would like to validate individual graphs (as per the SHACL spec).
* Better is to load the file into a `Dataset` and then iterate over each contained graph for validation purposes. This is a more involved fix that requires the loader to always load into a Dataset, and then the validator should iterate over each graph contained in the dataset.

[1] https://github.com/RDFLib/pySHACL/blob/a42cb6b32c5d405ffceda21d990a9af1c7c8f66c/pyshacl/rdfutil/load.py#L134

**Comment by ashleysommer** [comment]
Hi @RinkeHoekstra 
Thanks for the report.

Better handling of named graphs is actually something I've been wanting to address in pySHACL for some time. There are some named-graph-specific niche features of the SHACL spec that aren't implemented simply because we don't currently handle named graphs well.

To he honest, I didn't know it is possible for JSON-LD files to contain multiple named graphs. I've personally never come across a JSON-LD file with multiple graphs. Are you able to please attach or link to an example of a JSON-LD file that exhibits this described behavior?

You're right, the best solution is to load all named graphs into a Dataset, then validate each graph individually and potentially produce a separate validation report for each named graph too.

**Comment by ashleysommer** [comment]
Hi @RinkeHoekstra 
Just FYI, I've started work on this feature now. It will be full-support like suggestion 3 in initial post.

**Comment by ashleysommer** [comment]
Hi @RinkeHoekstra 
Good news. The latest version of pySHACL (v0.11.0) has support to what we've discussed above.
If the feature is still applicable to your use-case, can you please test it to ensure it does what is expected.

Fixed via https://github.com/RDFLib/pySHACL/commit/034b213a4fc7b1f96737e40c34096a568d5dd8fa

**Comment by RinkeHoekstra** [comment]
Hi Ashley,

That's great news. Thank you very much. I'll let you know if it doesn't
work.

Best,
Rinke
