### ISSUE TITLE
Validation Failure - All potentially pre-bound variables must be selected from a nested SELECT query. Don't forget to include variable `$this` in your SELECT arguments.

### ISSUE THREAD

**Issue by henrieglesorotos** [RDFLib/pySHACL#277]
We have two custom constraints for our SKOS concepts: 

```
## no two concepts should be given the same preferred lexical label for any given language tag
## NOTE: this one gets slow as the number of concepts grows. Might need to remove it for large taxonomies.

:ConceptUniquePrefLabelValues
    a sh:NodeShape ;
    sh:targetClass skos:Concept ;
    sh:sparql [
        a sh:SPARQLConstraint ;
        sh:message "Two concepts have the same label (in the same language)" ;
        sh:prefixes :prefixes ;
        sh:select """
            PREFIX skos:   <http://www.w3.org/2004/02/skos/core#>

            SELECT $this ?value
            {
                {
                    SELECT ?value
                    WHERE
                    {
                        ?concept a skos:Concept ;
                            skos:prefLabel ?prefLabel .
                        BIND(lcase(?prefLabel) AS ?value)
                    }
                    GROUP BY ?value
                    HAVING (COUNT(DISTINCT ?concept) > 1)
                }
                $this skos:prefLabel ?prefLabel .
                FILTER (lcase(?prefLabel) = ?value)
            }
            """ ;
    ] .

## no two collections should be given the same preferred lexical label for any given language tag
## NOTE: this one gets slow as the number of concepts grows. Might need to remove it for large taxonomies.

:CollectionUniquePrefLabelValues
    a sh:NodeShape ;
    sh:targetClass skos:Concept ;
    sh:sparql [
        a sh:SPARQLConstraint ;
        sh:message "Two collections have the same label (in the same language)" ;
        sh:prefixes :prefixes ;
        sh:select """
            PREFIX skos:   <http://www.w3.org/2004/02/skos/core#>

            SELECT $this ?value
            {
                {
                    SELECT ?value
                    WHERE
                    {
                        ?concept a skos:Collection ;
                            skos:prefLabel ?prefLabel .
                        BIND(lcase(?prefLabel) AS ?value)
                    }
                    GROUP BY ?value
                    HAVING (COUNT(DISTINCT ?concept) > 1)
                }
                $this skos:prefLabel ?prefLabel .
                FILTER (lcase(?prefLabel) = ?value)
            }
            """ ;
    ] .
 ```   
 
 We get the above warning. This works fine when using Jena CLI. Any ideas? 
 
 ```
 poetry show pyshacl
 name         : pyshacl
 version      : 0.28.1
 description  : Python SHACL Validator

dependencies
 - importlib-metadata >6
 - owlrl >=6.0.2,<7
 - packaging >=21.3
 - prettytable >=3.5.0
 - rdflib >=6.3.2,<8.0
 ```

**Comment by ashleysommer** [comment]
Hi @henrieglesorotos 
The error message tells you exactly what the problem is and how to fix it.

The SHACL spec states SPARQL sub-queries must return all potentially-pre-bound variables. In other words, sub-queries (nested SELECT statements) _MUST_ have the potentially pre-bound variables in their return list.
See Appendix A of the SHACL spec for more information. https://www.w3.org/TR/shacl/#pre-binding

In this case, you need to add `$this` to the subquery return variables, so it is available to use in the outer query, it is exactly what the error message says:
> From a nested select, don't forget to include variable `$this` in your SELECT.

**Comment by henrieglesorotos** [comment]
Thanks @ashleysommer!

**Comment by namedgraph** [comment]
@ashleysommer if you add `$this` to the sub-query, the resulting SPARQL query is not valid. You can check on https://sparql.org:
```
Non-group key variable in SELECT: ?this
```

**Comment by ashleysommer** [comment]
@namedgraph Right, because it is a query that has GROUP BY, you'll also need to add $this to the GROUP BY list.

**Comment by namedgraph** [comment]
Correct, but then the intent of the query is not the same as it was originally.

**Comment by ashleysommer** [comment]
It the same. The `$this` is bound to exactly one value (the `focusNode`) so having it in the GROUP BY does not change the way the groups are aggregated, the results are identical.

The reason this is required is because of the way SPARQL query engines tread Pre-bound variables. There are not the same as a `VALUES` clause.
The pre-bound variables are set to exist in the solution table before the SPARQL query starts.
SPARQL queries are evaluated from the inside out, so the subquery is evaluated first, and it starts with `$this=focusNode` in its solution table. The only way for the outer query to see `$this` is for the subquery to project it out.
