### ISSUE TITLE
PySHACL considers non-conforming datagraph to be conforming 

### ISSUE THREAD

**Issue by mdw00d** [RDFLib/pySHACL#29]
The attached files illustrate the behavior I am seeing.  The W3C validator (https://shacl.org/playground/) does flag this as non-conforming, so I am trusting this is not operator error on my part.

The shacl graph includes a property shape defined as follows:
```
 ex:Func  a       owl:Class , sh:NodeShape ;
        rdfs:label       "Func" ;
        rdfs:subClassOf   ex:Function ;
        sh:property      [ a         sh:PropertyShape ;
                           sh:class   ex:FuncParam_Func_a ;
                           sh:path    ex:hasParameter ;
                           sh:minCount 1;
                           sh:name	 "Func_a"
                         ] .
```
and the graph being validated includes 
```
test:FuncNode	a	ex:Func;
	ex:hasParameter test:FuncParam_b .
	
test:FuncParam_a	a	ex:FuncParam_Func_a .
test:FuncParam_b	a	ex:FuncParam_Func_b .
```

[simpleOnto.zip](https://github.com/RDFLib/pySHACL/files/3579927/simpleOnto.zip)

**Comment by ashleysommer** [comment]
Hi @mdw00d 
I've run some tests and have determined the source of the problem you are seeing.

It looks like you are using the "Implicit Class Target" mechanism to find the target nodes to apply the shape to, as described in section 2.1.3.3 SHACL spec here: https://www.w3.org/TR/shacl/#implicit-targetClass.

Your shape does not have a `sh:targetNode` or `sh:targetClass`, instead relying on the RDFS:Class of the Shape to be the targetClass to apply the shape to. As per this definition:
>Informally, if a shape is also declared to be a class in the shapes graph then all SHACL instances of this class are a target for the shape.
>
>If _s_ is a SHACL instance of **sh:NodeShape** or **sh:PropertyShape** in an RDF graph _G_ and _s_ is also a SHACL instance of **rdfs:Class** in _G_

Unfortunately this doesn't apply to your shape because you have `ex:Func` defined as type of `owl:Class`, not `rdfs:Class`.

Of course, `owl:Class` is a subproperty of `rdfs:Class`, but that is never inferred in the shapes graph because in pyshacl, as per SHACL best-practice, no inferencing (entailment) rules are ever allowed to run against the shapes graph.

So to solve your problem, simply change the definition of ex:Func to:
```
 ex:Func  a       owl:Class , rdfs:Class , sh:NodeShape ;
```

**Comment by ashleysommer** [comment]
I'm guessing the SHACL playground JS tool has a slightly relaxed interpretation of the wording in section 2.1.3.3, so perhaps checks for not only rdfs:Class but also owl:Class, when finding implicit class shapes in the shapes file.

**Comment by mdw00d** [comment]
Okay, thanks.   I am using a third-party tool to generate the SHACL, and unfortunately it does not add the rdfs:Class assertions, so I guess I will need to massage its output.

Again, thanks for taking a look at this.

**Comment by ashleysommer** [comment]
@mdw00d Can you let me know the name of the third-party tool you're using to generate the SHACL?
If it is a popular tool, and it generates slightly incompatible Shapes, then I should probably fix pySHACL so that it works with its outputs (or communicate with the upstream developers to get it fixed on their end).

**Comment by mdw00d** [comment]
I used TopQuadrant's EDG product.

Thanks again for your assistance.

**Comment by ashleysommer** [comment]
@mdw00d 
After communicating with the developers at TopQuadrant, we've decided on a fix for this in pySHACL.
Your generated SHACL Shapesfile will now work correctly as of pySHACL v0.11.1 (just released).

**Comment by ashleysommer** [comment]
Fixed via https://github.com/RDFLib/pySHACL/commit/5b8ffecbbb9b99503ea9d757cc3777afc59554c0

**Comment by mdw00d** [comment]
Thanks!
