### ISSUE TITLE
Monolithic file generates report, split .ttl files do not.

### ISSUE THREAD

**Issue by James-Hudson3010** [RDFLib/pySHACL#46]
I have a gist with all of the relevant files at: https://gist.github.com/James-Hudson3010/2588d9b17dd33e15922122b8b5cf1bd7

If I execute:

```
$ pyshacl -a -f human employees.ttl
```

I get the following, correct validation report...

```
Validation Report
Conforms: False
Results (3):
Constraint Violation in MaxInclusiveConstraintComponent (http://www.w3.org/ns/shacl#MaxInclusiveConstraintComponent):
	Severity: sh:Violation
	Source Shape: hr:jobGradeShape
	Focus Node: d:e4
	Value Node: Literal("8", datatype=xsd:integer)
	Result Path: hr:jobGrade
Constraint Violation in DatatypeConstraintComponent (http://www.w3.org/ns/shacl#DatatypeConstraintComponent):
	Severity: sh:Violation
	Source Shape: hr:jobGradeShape
	Focus Node: d:e3
	Value Node: Literal("3.14", datatype=xsd:decimal)
	Result Path: hr:jobGrade
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: hr:jobGradeShape
	Focus Node: d:e2
	Result Path: hr:jobGrade
```

However, if I split employees.ttl into three files containing the schema, shape, and instance data and run:

```
pyshacl -s shape.ttl -e schema.ttl -a -f human instance.ttl
```

the result is:

```
Validation Report
Conforms: True
```

I assume I am calling pyshacl correctly.

**Comment by James-Hudson3010** [comment]
I believe I understand part of what is going on, but not the reasons behind it.

When one splits into three separate parts, the shacl_graph does not contain the ont_graph information and cannot be processed correctly. 

A simple hack that fixes the problem is one line of code in the Validator __init__ code.

```
        **shacl_graph = mix_datasets( shacl_graph, self.ont_graph )**

        if shacl_graph is None:
            shacl_graph = clone_graph(data_graph, identifier='shacl')
        assert isinstance(shacl_graph, rdflib.Graph),\
            "shacl_graph must be a rdflib Graph object"
        self.shacl_graph = ShapesGraph(shacl_graph, self.logger)
```

basically, I add the ont_graph to the shacl_graph and it works as expected.

Obviously, there are some more checks that need to go in here for a complete solution and there may be other issues I have not yet considered.

**Comment by ashleysommer** [comment]
Hi @James-Hudson3010 

Yes, your assessment is correct, in pySHACL the `shacl_graph` does not get any `ont_graph` triples mixed in.
Keep in mind the extra-ontology-graph feature (`ont_graph`) was specifically introduced for the purpose to keep DataGraph files smaller, and the practical reality that DataGraph files cannot always be relied on to contain all of the ontology definitions required for validation to work properly, especially if the Datagraph was supposed to be pre-inferenced before validation.

The `ont_graph` was never intended to work with the SHACL Shapes Graph. Its considered bad practice for a shacl validator to modify the Shapes graph in any way before validation, because that can cause unforeseen validation issues (as you have alluded to).

If a SHACL Shapes Graph requires any ontological definitions in order to work correctly then it makes sense that the author should include those definitions either directly in the SHACL Shapes source file, or via an `owl:imports` statement in the SHACL shapes file.

I hope that has helped.

**Comment by James-Hudson3010** [comment]
It does. Thank you.
