### ISSUE TITLE
validation with superclass constraints

### ISSUE THREAD

**Issue by ajhewett** [RDFLib/pySHACL#6]
pyshacl seems to ignore constraints defined on a superclass when validating an instance of a subclass.  e.g given the SHACL
```
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix ex: <http://example.com/ex#> .

ex: a owl:Ontology ;
    rdfs:label "Example"@en ;
    rdfs:comment "Example"@en ;
    owl:versionInfo "" ;
    sh:declare [ sh:namespace "http://example.com/ex#" ;
            sh:prefix "ex" ] .

ex:Parent a rdfs:Class ;
    rdfs:isDefinedBy ex: ;
    rdfs:comment "The parent class"@en ;
    rdfs:subClassOf owl:Thing .

ex:ParentShape a sh:NodeShape ;
    rdfs:isDefinedBy ex: ;
    sh:property [
        sh:datatype xsd:string ;
        sh:path ex:name ;
        sh:maxCount 1 ;
        sh:minCount 1 ;
    ] ;
    sh:targetClass ex:Parent .

ex:Child a rdfs:Class ;
    rdfs:isDefinedBy ex: ;
    rdfs:comment "The child class"@en ;
    rdfs:subClassOf ex:Parent .

ex:ChildShape a sh:NodeShape ;
    rdfs:isDefinedBy ex: ;
    rdfs:subClassOf ex:ParentShape ;
    sh:property [
        sh:datatype xsd:integer ;
        sh:path ex:age ;
        sh:maxCount 1 ;
        sh:minCount 1 ;
    ] ;
    sh:targetClass ex:Child .
```
Validating a json-ld instance of ``Child`` that is missing the ``name`` property from ``Parent`` against the above SHACL
```
{
    "@context": {
        "@vocab": "http://example.com/ex#"
    },
    "@type": "Child",
    "age": 3
}
```
does not find a violation.  I had expected that validating a subclass instance would also include constraints from the superclass.  

Is this a misunderstanding of SHACL on my part or an issue with pyshacl?

**Comment by ashleysommer** [comment]
@ajhewett Thanks for taking the time to raise this issue.

The problem you are describing is one of pre-inferencing.
A couple of questions:
1. How are you invoking pySHACL, via the command line or using the library in a larger project?
2. Are you specifiying and pre-inferencing options, like "rdfs", "owlrl', or "both"?

The `ParentShape` constraint is not applied to the instance of `Child`, because the target graph does not know that Child inherits the rules of Parent, even though the RDFS `subClassOf` predicate is used in the Shape file.

In order for the `ParentShape` rule to apply to `Child`, there must exist a triple (in the target graph) of `(child_instance_id, "rdf:type", ex:Parent")`. This is normally applied by running the RDFS influencing step before validation.

In this case however, this would not work, because the RDFS pre-inferencing step is only applied to the Data Graph (the target graph), no RDFS declarations from the SHACL Shapes file are pulled into the Data Graph during the pre-inferencing step.

You would need to put this triple into the target graph:
```
(ex:Child, rdfs:subClassOf. ex:Parent)
``` 
Then run ensure you run the RDFS pre-inferencing step before validating, in order to get the result you are expecting.

Note, this same behaviour exists on the official SHACL Playground webapp here:
http://shacl.org/playground/
It uses an entirely different SHACL implementation, and gives the same result you are seeing here.

**Comment by ajhewett** [comment]
@ashleysommer many thanks for your prompt response.  Very helpful and informative. :thumbsup:

To answer your questions:
1. I am using the python library within a larger project.
2. I specify the "rdfs" inferencing option and also tried the others.

My pyshacl library call looks like:
```python
r = pyshacl.validate(target_graph=dataGraph.default_context, shacl_graph=shaclGraph, inference='rdfs', abort_on_error=False, meta_shacl=True, debug=False)
```

I did not realize that inferencing is only applied to the target graph with the implication that RDFS Classes declared in the SHACL Shapes graph are not automatically used.

Your suggestion to add a ``(ex:Child, rdfs:subClassOf. ex:Parent)`` triple to the target graph does indeed give the expected result.  However, my use-case is validating json-ld data returned in a http response so I would prefer to avoid modifying the response if possible.

After some further experimentation I have been able to achieve a similar effect by enhancing the ``ParentShape`` to also target the ``Child`` class in addition to the ``Parent`` class.  This is easier since I control the SHACL Shapes file.

I will close this issue since it is clearly not a pyshacl problem.

**Comment by ashleysommer** [comment]
@ajhewett 
I've been thinking about your use-case, and it does absolutely make sense for some applications of SHACL to have the RDFS Class relationships defined in the same file as the SHACL Shapes, and for the Data File to be bare instances of those classes.

I will think about how we could make that work, potentially by copying any `rdfs:Class` declarations from the SHACL graph into the Data graph _before_ inferencing.
What I do know is that we can't run RDFS inferencing over the SHACL Shapes graph itself because a lot of the extra triples the inferencing engine adds to the SHACL Shapes and rules break the expected behaviour of those rules.

This new feature would need to be enabled via a flag, because it is probably not something users would expect to happen by default.

**Comment by ashleysommer** [comment]
@ajhewett 
The latest release of pySHACL (v0.9.9) has a new feature that will potentially solve the problem we were seeing above.

There is a new option to pass into the validator another external file containing extra ontological information, that is needed by the data graph in order for inferencing to proceed correctly.

In the example above, we would have an ontology.ttl file with 
```
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix ex: <http://example.com/ex#> .

ex:Parent a rdfs:Class ;
    rdfs:isDefinedBy ex: ;
    rdfs:comment "The parent class"@en ;
    rdfs:subClassOf owl:Thing .

ex:Child a rdfs:Class ;
    rdfs:isDefinedBy ex: ;
    rdfs:comment "The child class"@en ;
    rdfs:subClassOf ex:Parent .
```

Then pass that file into the validator with `ont_graph="ontology.ttl"` along with the shacl file and the target data file. Now the data graph does not need to be modified before running the validator on it, and it can be simply a bare data snippet that is an instance of those classes defined in the ontology.
