### ISSUE TITLE
Options to ignore warnings?

### ISSUE THREAD

**Issue by jbkoh** [RDFLib/pySHACL#64]
Hi there, I wonder if I can ignore `ValidationResults` with `sh:resultSeverity sh:Warning`. I can of course parse out the result graph to filter them out, but it'd be convenient to pass a parameter like `ignore_warning=True` so that `conforms` does not return `False` for warnings.

Thanks!

**Comment by ashleysommer** [comment]
Hi @jbkoh
This is a great feature request, and to be honest is one of those things that should've been there the whole time.

When initially implementing the basics of pyshacl, I thought about always ignoring warnings, but the shacl spec is clear that _any_ validation result (regardless of severity) will cause conformance to be false.

But we can definitely put it behind an option, so you can opt in to ignoring warnings.

Once that's implemented, I'll push out a new version and let you know.

**Comment by jbkoh** [comment]
Good to know it came from the SHACL spec. Thanks for the information and look forward to the feature! Thanks! (You may close this issue if preferred.)

**Comment by ashleysommer** [comment]
Hi @jbkoh 
Just want to let you know I haven't forgotten about this feature request. It is on my todo list, but actually turns out to be a little bit harder to implement than I thought. I put it aside to work on the SHACL-JS implementation, but now that is released I might get time to look into this again.

**Comment by ashleysommer** [comment]
Hi @jbkoh 
Just FYI, this feature is now merged. You can use it in v0.14.5 of PySHACL.
Its still kind-of experimental, but it passed all of the tests I threw at it.
The option is `allow_warnings=True` in the validator.
Note, despite the name, it allows (ignores) both `sh:Info` and `sh:Warning` validation results.
Let me know if you use it, and if you have any problems.

Fixed by https://github.com/RDFLib/pySHACL/commit/72027edb35d417ab1335b172df1c285b60c6c381
