### ISSUE TITLE
SHACL Advanced Feature support

### ISSUE THREAD

**Issue by gtfierro** [RDFLib/pySHACL#67]
Hi there! 

First off, thanks for the great work on pySHACL; we are using it for development on [Brick](https://github.com/BrickSchema/brick/). I was wondering if supporting [SHACL advanced features](https://www.w3.org/TR/shacl-af/) is on your roadmap? It would be great to take advantage of the inference features. Let me know if I can offer any support

**Comment by ashleysommer** [comment]
Hi @gtfierro 

PySHACL has supported The SHACL Advanced Features Spec since v0.10.0 released in August 2019.

The the main [README](https://github.com/RDFLib/pySHACL/blob/master/README.md) for instructions how to enable advanced features.

See the [PySHACL Features Matrix](https://github.com/RDFLib/pySHACL/blob/master/FEATURES.md) for details on what SHACL features are supported in PySHACL.

Finally, you can check the [changelog](https://github.com/RDFLib/pySHACL/blob/master/CHANGELOG.md) to see which version of PySHACL was the first ship any given feature. Eg, v0.10.0 brought SHACLRules and SPARQLRules from the advanced spec, v0.11.0 added `sh:SPARQLTarget` Custom Targets, v0.13.0 brought custom Expressions and SHACLFunctions, v0.13.1 had SHACLTargets and SPARQL-Targets, and finally the recently released v0.14.0 introduced support for the entire SHACL-JS extension spec.

**Comment by gtfierro** [comment]
Wow! I'm blind :). I was searching for "shacl-af"; didn't think to search
for 'advanced'. Thanks for pointing me in the right direction!
