### ISSUE TITLE
how to validate a property whose value is an URL?

### ISSUE THREAD

**Issue by sanuann** [RDFLib/pySHACL#72]
I have this data graph here: https://tinyurl.com/ydltptm9
how should I validate it such that the value for "contentUrl" should be an URL only?

i have used this shape:
```
sh:property [ sh:nodeKind sh:IRI ;
            sh:minCount 1 ;
            sh:path schema:contentUrl ] .
```

with the above shape, it `conforms: True` when the value is an URL. however, it also says `conforms: True` when I set the value to any string eg. `contentUrl: "abc"`

Why does the validator accept any random string as an URI?

**Comment by ashleysommer** [comment]
Hi @sanuann
I've done some basic tests on my code and the `sh:nodeKind` rule is working normally in PySHACL.

The shape you've provided is incomplete, can you please show the full SHACL Shape you are using to validate this data?

And the data graph you've provided is also incomplete, there are missing prefixes and that shape Graph would not be able to validate against any shape.

**Comment by sanuann** [comment]
hi @ashleysommer thanks for taking the time to look into my issue. here is the original data graph:
https://github.com/ReproNim/reproschema/blob/dbd1e36a17f59af06fbca864400f71f90ab93ad2/examples/activities/items/item2.jsonld
and here is the full SHACL shape: https://github.com/ReproNim/reproschema/blob/dbd1e36a17f59af06fbca864400f71f90ab93ad2/validation/reproschema-shacl.ttl

if I change the value to a string `contentUrl: "abc"` it still conforms True. why?

**Comment by ashleysommer** [comment]
Hi @sanuann 
I've looked quite deeply into this issue, and I believe I've found where the problem is coming from.
You have defined in your context document:
```
     "contentUrl": {
         "@id": "schema:contentUrl",
         "@type": "@id"
     },
```
The `@type: @id" declaration causes all untyped values of `reposchema:contentUrl` to be coerced to a URI.
For example:
```
    "video": {
      "@type": "VideoObject",
      "contentUrl": "abc"
    },
```
That gets expanded to equivalent triples:
```
reposchema:video rdf:type reposchema:VideoObject
reposchema:video reposchema:contentUrl <file://path/to/item2.jsonld#abc>
```
Notice the JSON-LD parser has turned `"abc"` into `<file://path/to/item2.jsonld#abc>`.
That is why it is still passing the `sh:nodeKind sh:IRI` constraint during validation.

You can force a string-literal into that property for testing:
```
    "video": {
      "@type": "VideoObject",
      "contentUrl": { "@value": "abc" }
    },
```
Now you see the following output as expected:
```
Constraint Violation in NodeKindConstraintComponent (http://www.w3.org/ns/shacl#NodeKindConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path schema:contentUrl ]
	Focus Node: [ rdf:type reproschema:VideoObject ; schema:contentUrl Literal("abc") ]
	Value Node: Literal("abc")
	Result Path: schema:contentUrl
	Message: Value is not of Node Kind sh:IRI

Constraint Violation in NodeConstraintComponent (http://www.w3.org/ns/shacl#NodeConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:node reproschema:MediaObjectShape ; sh:path schema:video ]
	Focus Node: <file:///home/som05d/CODE/RDF/pySHACL/test/issues/item2.jsonld>
	Value Node: [ rdf:type reproschema:VideoObject ; schema:contentUrl Literal("abc") ]
	Result Path: schema:video
	Message: Value does not conform to Shape reproschema:MediaObjectShape
```

**Comment by sanuann** [comment]
so in the context if I remove `@type: @id` then even an URI value is taken as a Literal. The equivalent triples look like this:

```
schema:video rdf:type schema:VideoObject
schema:video schema:contentUrl  "http://media.freesound.org/sample-file.mp4"@en
```
and the validator would fail for this.

How do I ensure that the value to contentUrl will only be an URl?

**Comment by ashleysommer** [comment]
Good question. To be honest, I'm not sure. I'm not a JSON-LD expert, I try to avoid JSON-LD as much as possible.

Does this work?:
```
"video": {
    "@type": "VideoObject",
    "contentUrl": { "@id": "http://media.freesound.org/sample-file.mp4" }
},
```

**Comment by sanuann** [comment]
yes, that works. I am not sure either how this whole thing works 😄 
Thanks for your time though.

**Comment by sanuann** [comment]
@ashleysommer one last doubt. if I define the `@type: "xsd:anyURI"` for `contentUrl` in the context (we actually want this instead of type id), the triple looks like this for any value(string, integer or URI). here I have used a string "abc". :
```
schema:video rdf:type schema:VideoObject
schema:video schema:contentUrl  "abc"^^<http://www.w3.org/2001/XMLSchema#anyURI> .
```
and the validator looks like this for that property:
```
reproschema:MediaObjectShape a sh:NodeShape ;
    sh:closed true;
    sh:ignoredProperties ( rdf:type ) ;
    sh:property [ sh:datatype xsd:anyURI ;
            sh:minCount 1 ;
            sh:path schema:contentUrl ] .
```

the validator says conforms `True` for any value. Isn't the validator supposed to check the actual value in `"..."` in the triple to decide `True` or `False`?

**Comment by ashleysommer** [comment]
Good question. Short answer, is: No, when enforcing `xsd:anyURI` the sh:datatype constraint does not look at the actual value of the Literal. That is in line with the SHACL specification (see here: https://www.w3.org/TR/shacl/#DatatypeConstraintComponent).
> A literal matches a datatype if the literal's datatype has the same IRI and, for the datatypes supported by SPARQL 1.1, is not an ill-typed literal. 

It will still require that the datatype is `xsd:anyURI` but it can't check if the value matches the datatype (ie, how could it do that for any arbitrary datatype?).

On the other hand, if you've specified a `sh:datatype` that is supported by the SPARQL 1.1 spec, then it _can_ check the actual value, so that is xsd:string, xsd:integer, xsd:float, xsd:double and xsd:decimal.
