### ISSUE TITLE
Need help understanding some validation results

### ISSUE THREAD

**Issue by bbartley** [RDFLib/pySHACL#73]
Hello, myself and @tcmitchell are getting some validation results that seem counterintuitive to me.  It might be a bug, or maybe just my misunderstanding of some nuance of OWL.  Can I get a sanity check please?

I have created a test case in which an `sbol:Component` instance points to an invalid type.  The shape is defined as follows:
```
shacl:ComponentHasFeatureShape
        a sh:NodeShape ;
        sh:targetClass sbol:Component ;
        sh:property [
                sh:path sbol:hasFeature ;
                sh:class sbol:Feature ;
        ] ;
```
However, when the following property definition is included in my ontology file, the validation counterintuitively _passes_.
```
sbol:hasFeature
  a owl:ObjectProperty ;
  rdfs:domain sbol:Component ;
  rdfs:range sbol:Feature ;
.
```
When I remove this property definition from the ontology, specifically the _rdfs:range_, my test case again fails as designed and expected.  Why does including the _range_ effectively neutralize the rule encoded by my shape?

Do you see anything obvious about why I should be observing this behavior?  (I can also provide minimal test case files if helpful).  Thanks in advance!

**Comment by ashleysommer** [comment]
Hi @bbartley 
Yep, this is indeed a counterintuitive example. But unfortunately its not a bug. PySHACL and OWL are both working as intended here.
The key is the way `rdfs:range` works when expanding the triples.
The RDFS inferencer (or OWL inferencer) will add class types to your feature instance such that it matches the `rdfs:range` given.

For example (ignoring SHACL and PySHACL for now):
Ontology
```
ex:Human a rdfs:Class .
ex:Animal a rdfs:Class .
ex:hasPet
  a owl:ObjectProperty ;
  rdfs:domain ex:Human ;
  rdfs:range ex:Animal ;
.
```

DataGraph
```
ex:milly a ex:Cat .

ex:stacey a ex:Human ;
  ex:hasPet ex:milly .
```

When you run an RDFS or OWL inferencing pass over the DataGraph, there will be a new triple emitted:
```
ex:milly a ex:Animal .
```
Even though `ex:Cat` is not defined as subclassof `ex:Animal`, the inference engine will add it in order to satisfy the `rdfs:range ex:Animal` rule.

This happens because the ontological constructs in RDFS and OWL are statements of fact. If you say "all values of ex:hasPet are ex:Animal" and you also say "stacey hasPet milly", therefore milly must be a `ex:Animal` to satisfy the truth of the `rdfs:range`.

I hope that makes sense. As you can see it is the opposite of SHACL in some sense because in SHACL your Shapes and Constraints are will generate failing Validation if they do not match what is stated.

**Comment by ashleysommer** [comment]
Don't know if you're interested, but I want to suggest a book that helped me understand some of this OWL and RDFS stuff when I was first learning about how it all works.
https://www.elsevier.com/books/semantic-web-for-the-working-ontologist/allemang/978-0-12-385965-5
I found that book was able to introduce concepts in a very easy to understand way, and much better than reading W3C specs and trying to wrap your head around the language in those documents.
There is an ebook version available, but you can probably find chapter excerpts around online.

**Comment by tcmitchell** [comment]
@ashleysommer Thank you! We were using `inference='rdfs'` in our call to `pyshacl.validate`. Dropping that argument fixes the issue we were having, and lists out the violations we were expecting to see. Your explanation was terrific, thanks for taking so much time to explain it. I can also see the asserted facts (triples) in the graph if I use the `inplace=True` argument to `pyshacl.validate` when using `inference='rdfs'`.

Thanks for the book recommendation too!
