### ISSUE TITLE
Validation report omits lower level reports

### ISSUE THREAD

**Issue by Martijn-Y-ai** [RDFLib/pySHACL#85]
When executing nested shapes, I noticed that only a validation result is generated for the topmost violating shape. Looking into the code, I found the culprit to be in `shape_based_constraints.py` at lines 175-179. I would suggest to just replace those lines with
```
_reports.extend(_r)
_non_conformant = not _is_conform
```

For the attached data and schema, that would change the validation report from:
```
[] a sh:ValidationReport ;
    sh:conforms false ;
    sh:result [ a sh:ValidationResult ;
            sh:focusNode ex:something ;
            sh:resultMessage "Value does not conform to Shape [ rdf:type sh:NodeShape ; sh:property [ rdf:type sh:PropertyShape ; sh:minCount Literal(\"1\", datatype=xsd:integer) ; sh:name Literal(\"hasDefinitionShape\") ; sh:path skos:definition ] ]" ;
            sh:resultPath ex:specification ;
            sh:resultSeverity sh:Violation ;
            sh:sourceConstraintComponent sh:NodeConstraintComponent ;
            sh:sourceShape [ a sh:PropertyShape ;
                    sh:maxCount 1 ;
                    sh:minCount 1 ;
                    sh:name "specificationShape" ;
                    sh:node [ a sh:NodeShape ;
                            sh:property [ a sh:PropertyShape ;
                                    sh:minCount 1 ;
                                    sh:name "hasDefinitionShape" ;
                                    sh:path skos:definition ] ] ;
                    sh:path ex:specification ] ;
            sh:value ex:someType ] .
```
To:
```
[] a sh:ValidationReport ;
    sh:conforms false ;
    sh:result [ a sh:ValidationResult ;
            sh:focusNode ex:someType ;
            sh:resultMessage "Less than 1 values on ex:someType->skos:definition" ;
            sh:resultPath skos:definition ;
            sh:resultSeverity sh:Violation ;
            sh:sourceConstraintComponent sh:MinCountConstraintComponent ;
            sh:sourceShape [ a sh:PropertyShape ;
                    sh:minCount 1 ;
                    sh:name "hasDefinitionShape" ;
                    sh:path skos:definition ] ] .
```
[test_data.txt](https://github.com/RDFLib/pySHACL/files/6854443/test_data.txt)
[test_schema.txt](https://github.com/RDFLib/pySHACL/files/6854410/test_schema.txt)
[test_vr.txt](https://github.com/RDFLib/pySHACL/files/6854414/test_vr.txt) to be renamed to `test_vr.py`, but Github does not allow me to upload .py files...

Why are the fails from the node ignored in the original code and is the proposed change acceptable?

**Comment by ashleysommer** [comment]
Hi @Martijn-Y-ai 
Have you tested your data and schema on other SHACL validation engines to see their behaviour? I think you'll find they emit the same results as PySHACL.

You'll notice in at line 175 in that `shape_based_constraints.py` file there is a code comment, which specified that this behaviour is intentional:
`# ignore the failes from the node, and create our own fail`.

This behaviour is specific to the NodeConstraintComponent (`sh:node`). Please see the SHACL Specification for details of how `sh:node` is supposed to be used. Its definition states:
> ... if _v_ does not conform to `$node`, there is a validation result with _v_ as `sh:value`.

That is exactly what is happening here. NodeConstraintComponent checks if the data conforms to  the given NodeShape, and if it doesn't it emits its _own_ failure, not that of the given NodeShape. The validation failure of the inner NodeShape is _not_ emitted to the result graph.

That is further clarified further down in a different section:
> Note that there is an important difference between sh:property and sh:node: If a value node is violating the constraint, then there is only a single validation result for sh:node for this value node, with sh:NodeConstraintComponent as its sh:sourceConstraintComponent. On the other hand side, there may be any number of validation results for sh:property, and these will have the individual constraint components of the constraints in the property shape as their values of sh:sourceConstraintComponent. 

If you run PySHACL with debug mode turned on (with --debug in the CLI, or debug=True in the module), then you _will_ see the validation failure of the inner NodeShape printed in your terminal, but it still will not be emitted to the result graph.

If that is not the behaviour you are expecting, then you should not use `sh:node`. In practice, `sh:node` is rarely used, appearing only for very specific cases where that is what you want to happen.

There are two ways I can see to rewrite your text_schema Shape to remove the use of `sh:shape`.

This uses the [SHACL Property Paths](https://www.w3.org/TR/shacl/#property-paths) feature: 
```
ex:thingShape 
    a sh:NodeShape ;
    sh:targetClass ex:Thing ;
    sh:property [
        a sh:PropertyShape ;
        sh:name "specificationShape" ;
        sh:path ex:specification ;
        sh:minCount 1 ;
        sh:maxCount 1
    ] ;
    sh:property [
        a sh:PropertyShape ;
        sh:name "hasDefinitionShape" ;
        sh:path ( ex:specification skos:definition ) ;
        sh:minCount 1 
    ]  .  
``` 
This one uses nested PropertyShapes, and is more similar to your original example.
```
ex:thingShape 
    a sh:NodeShape ;
    sh:targetClass ex:Thing ;
    sh:property [
        a sh:PropertyShape ;
        sh:name "specificationShape" ;
        sh:path ex:specification ;
        sh:property [
                a sh:PropertyShape ;
                sh:name "hasDefinitionShape" ;
                sh:path skos:definition ;
                sh:minCount 1
            ]
        ] ;
        sh:minCount 1 ;
        sh:maxCount 1
    ]  .
```

**Comment by Martijn-Y-ai** [comment]
Thanks for the explanation and elaboration on the sh:node behavior! The solution with the property paths works for me.
