### ISSUE TITLE
Can pySHACL generate a SHACL graph from an RDFS graph?

### ISSUE THREAD

**Issue by SvenPVoigt** [RDFLib/pySHACL#86]
I read through the documentation and it appears that an ontology graph can be passed to the `validate` function, which I am assuming lets pySHACL check against RDFS constraints.

Is it also possible to convert a graph of RDFS objects to a SHACL graph? I am looking for a more object oriented schema representation like SHACL, which would be helpful for generating documentation and building classes in python.

**Comment by ashleysommer** [comment]
Hi @SvenPVoigt,

> I am assuming lets pySHACL check against RDFS constraints

You have misunderstood that feature. RDFS cannot impose constraints on your data.

The ability to pass in an ontology graph to PySHACL is for mixing the contents of the ontology with your datagraph in order to seed the inferencing step. This does not affect the Shapes Graph, and does not add new rules to the validation step.

Following from that, it is not possible for PySHACL to derive SHACL shapes from RDFS definitions.
