### ISSUE TITLE
validation with sh:closed

### ISSUE THREAD

**Issue by ajhewett** [RDFLib/pySHACL#9]
Given the Shapes Graph:
```
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix ex: <http://example.com/ex#> .

ex:Parent a rdfs:Class ;
    rdfs:isDefinedBy ex: ;
    rdfs:comment "The parent class"@en ;
    rdfs:subClassOf owl:Thing .

ex:ParentShape a sh:NodeShape ;
    rdfs:isDefinedBy ex: ;
    sh:property [
        sh:datatype xsd:string ;
        sh:path ex:name ;
        sh:maxCount 1 ;
        sh:minCount 1 ;
    ] ;
    sh:closed true ; 
    sh:ignoredProperties ( rdf:type ) ;    
    sh:targetClass ex:Parent .
```

and the Data Graph:
```
{
    "@context": {
        "@vocab": "http://example.com/ex#"
    },
    "@type": "Parent",
    "name": "Father",
    "dummy": "Dummy value"
}
```

I expect to see a sh:ClosedConstraintComponent validation failure because of ``(ex:ParentShape sh:closed, true)`` in the Shapes Graph  and the presence of the property ``"dummy": "Dummy value"`` in the Data Graph.

However, using the pyshacl (0.9.5) validate function no such validation failure is generated.  Instead the text result is:
```
Validation Report
Conforms: True
```

In http://shacl.org/playground/ the expected validation failure is produced.

**Comment by ashleysommer** [comment]
@ajhewett 
I've found and fixed this bug in `pyshacl`. Upgrade to release v0.9.6, and this should work for you now.

If you're interested,
The problem was that the `sh:closed` validator was looking for non-conformant predicate-object pairs on instances of `ParentShape` in the Shacl Shapes graph, rather than looking for them in the target data graph.

The test suite didn't pick up this bug because the vast majority of tests use a combined shacl shapes file and datagraph file. In which case, the shapes graph and the target data graph are the same file, so the rule worked regardless.

**Comment by ashleysommer** [comment]
Fixed by https://github.com/RDFLib/pySHACL/commit/b5ff4683afbe2a57e0392733f0a62ca4e3501808
